/**
 * @file file_io.h
 *
 * This is generated by parser_template_generator. If you edit this file,
 * don't run the generator in this directory. Run it in a different one and
 * then merge the results using a tool like diff.
 *
 * @date Sat Jul 19 18:26:30 2025
 * @author Chuck Tilbury
 *
 */

#ifndef _FILEIO_H_
#define _FILEIO_H_

#include <stdbool.h>
#include "string_buffer.h"

#define EOI -2

/**
 * @brief File data structure type
 *
 */
typedef struct _file_t_ {
    string_t* name;
    FILE* fp;
    int line;
    int column;
    bool is_open;
#ifdef USE_FLEX
    struct yy_buffer_state* buffer;
#else
    int ch;
#endif
    struct _file_t_* next;
} file_t;

#ifndef USE_FLEX
    void close_file(void);
    int get_char(void);
    int consume_char(void);
#else
    void update_numbers(void);
#endif
void open_file(const char* name);
int get_line_no(void);
int get_col_no(void);
const char* get_file_name(void);
file_t* get_file_buffer(void);
void push_file_buffer(file_t*);
file_t* pop_file_buffer(void);
const char* get_base_file_name(string_t* str);

#endif /* _FILEIO_H_ */
