/**
 * @file ./out/scanner/file_io.c
 *
 * This is generated by parser_template_generator. If you edit this file,
 * don't run the generator in this directory. Run it in a different one and
 * then merge the results using a tool like diff.
 *
 * @date Sat Jul 19 18:26:30 2025
 * @author Chuck Tilbury
 *
 */

#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <string.h>
#include <errno.h>

#include "macros.h"
#include "fileio.h"
#include "scanner.h"
#include "common.h"

static file_t* file_stack = NULL;

/**
 * @brief Open a file for input and push it on the file stack.
 *
 * @param name
 */
void open_file(const char* name) {

    ENTER;
    TRACE("search: \"%s\" \"%s\"", name, FILE_EXT);

    file_t* ptr = _ALLOC_TYPE(file_t);

    const char* fn = find_file(name, FILE_EXT);
    ptr->fp = fopen(fn, "r");
    if(ptr->fp == NULL)
        FATAL("cannot open input file: %s: %s", fn, strerror(errno));

    ptr->name = create_string(fn);
    ptr->line = 1;
    ptr->column = 1;
    ptr->is_open = true;
#ifdef USE_FLEX
    yyin = ptr->fp;
    ptr->buffer = yy_create_buffer(yyin, YY_BUF_SIZE);
    yy_switch_to_buffer(ptr->buffer);
#endif
    ptr->next = NULL;

    push_file_buffer(ptr);

    TRACE("open file: %s", fn);
#ifndef USE_FLEX
    consume_char();
#endif
    RETURN();
}

/**
 * @brief Pop the current file off of the stack and destroy it.
 *
 *
 */
void close_file(void) {

    ENTER;
    file_t* ptr = file_stack;
    if(ptr != NULL) {
        TRACE("%s\n", raw_string(ptr->name));
        if(ptr->next != NULL) {
            fclose(ptr->fp);
            destroy_string(ptr->name);
#ifdef USE_FLEX
            yy_delete_buffer(ptr->buffer);
#endif
            //file_stack = ptr->next;
            pop_file_buffer();
            _FREE(ptr);
        }
        else {
            ptr->is_open = false;
#ifndef USE_FLEX
            ptr->ch = EOF;
#endif
        }
#ifdef USE_FLEX
        if(file_stack->is_open)
            yy_switch_to_buffer(file_stack->buffer);
#endif
    }
    else {
        TRACE("no open file\n");
    }

    RETURN();
}

#ifndef USE_FLEX
int get_char(void) {

    ASSERT(file_stack != NULL, "uninitialized scanner");
    return file_stack->ch;
}

int consume_char(void) {

    ASSERT(file_stack != NULL, "uninitialized scanner");
    if(file_stack->ch != EOF) {
        if(file_stack->ch == '\n') {
            file_stack->line++;
            file_stack->column = 1;
        }
        else
            file_stack->column++;
    }

    file_stack->ch = fgetc(file_stack->fp);
    if(file_stack->ch == EOF)
        close_file();

    //fprintf(stderr, "%c", file_stack->ch);
    return file_stack->ch;
}
#endif

int get_line_no(void) {

    if(file_stack != NULL)
        return file_stack->line;
    else
        return -1;
}

int get_col_no(void) {

    if(file_stack != NULL)
        return file_stack->column;
    else
        return -1;
}

const char* get_file_name(void) {

    if(file_stack != NULL)
        return get_base_file_name(file_stack->name);
    else
        return NULL;
}

#ifdef USE_FLEX
// the others are given by scanner.h
extern int yycolno;
extern int prev_lineno;

void update_numbers(void) {

    int count = 0;
    for(char* tpt = yytext; *tpt != '\0'; tpt++)
        if(*tpt == '\n')
            count++;

    if(count != 0) {
        file_stack->line += count;
        file_stack->column = 1;
    }
    else
        file_stack->column += yyleng;
}
#endif

file_t* get_file_buffer(void) {

    if(file_stack)
        return file_stack;
    else
        return NULL;
}

void push_file_buffer(file_t* ptr) {

    if(file_stack != NULL)
        ptr->next = file_stack;
    file_stack = ptr;
}

file_t* pop_file_buffer(void) {

    if(file_stack != NULL)
        file_stack = file_stack->next;

    return file_stack;
}

const char* get_base_file_name(string_t* str) {

    char* tpt = strrchr(str->buffer, '/');
    if(tpt != NULL && tpt[1] != '\0')
        return &tpt[1];
    else
        return str->buffer;
}
